### ISSUE TITLE
Packs download return 404

### ISSUE THREAD

**Issue by wpigoury** [Magisk-Modules-Repo/energizedprotection#20]
Impossible to apply any pack as they all return a 404 error now.
Will there be an update of the module?

Thanks.

**Comment by RupeshDagur** [comment]
Hi dear, this is not permanent solution but yes it will work to you , i have made .gz file of Unified pack and Regional pack , you can download the same from https://www.mediafire.com/file/fk0i11mecwf27u9/hosts.gz/file
after download go to your android file manager Internal storage\EnergizedProtection
and paste the same file that you have downloaded

now just run energized through any terminal emulator 
and choose any pack it will show you server error but because you have placed hosts file at it location so it will pick up the host file and will show you the result 
means it will install the pack to your devie

just reboot your device , you are done
thanks me later

**Comment by wpigoury** [comment]
Thanks for the effort but I switched back to AdAway and I'll wait for a proper fix if ever.

**Comment by wuchenkang** [comment]
Same issue. Sorry but when will this problem be fixed?

**Comment by wuchenkang** [comment]
> Same issue. Sorry but when will this problem be fixed?

Maybe the script in `system/bin` needs an update?

**Comment by AdroitAdorKhan** [comment]
Try the latest update. Everything has been fixed with the new base.

**Comment by wuchenkang** [comment]
It works fine for me, thanks for your work!

**Comment by wpigoury** [comment]
Working great now. Glad to have Energized back, thanks.
